name: Deploy Documentation to Pages

on:
    release:
        types:
            - published

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 10
            - name: Checkout code
              uses: actions/checkout@master
            - name: Build Package
              run: |
                  yarn
                  yarn docs
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
